# Daniel Nicolas Gisolfi
# 2019-11-20
# Reverse Proxy

version: "2"
services: 
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    container_name: reverse-proxy
    volumes:
      - ./ssl:/etc/nginx/ssl